// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocksapi

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/core/v1"
)

// MockServiceAPI is an autogenerated mock type for the ServiceAPI type
type MockServiceAPI struct {
	mock.Mock
}

type MockServiceAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceAPI) EXPECT() *MockServiceAPI_Expecter {
	return &MockServiceAPI_Expecter{mock: &_m.Mock}
}

// GetServiceByName provides a mock function with given fields: ctx, namespace, name
func (_m *MockServiceAPI) GetServiceByName(ctx context.Context, namespace string, name string) (*v1.Service, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceByName")
	}

	var r0 *v1.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1.Service, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1.Service); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceAPI_GetServiceByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceByName'
type MockServiceAPI_GetServiceByName_Call struct {
	*mock.Call
}

// GetServiceByName is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockServiceAPI_Expecter) GetServiceByName(ctx interface{}, namespace interface{}, name interface{}) *MockServiceAPI_GetServiceByName_Call {
	return &MockServiceAPI_GetServiceByName_Call{Call: _e.mock.On("GetServiceByName", ctx, namespace, name)}
}

func (_c *MockServiceAPI_GetServiceByName_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockServiceAPI_GetServiceByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServiceAPI_GetServiceByName_Call) Return(_a0 *v1.Service, _a1 error) *MockServiceAPI_GetServiceByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceAPI_GetServiceByName_Call) RunAndReturn(run func(context.Context, string, string) (*v1.Service, error)) *MockServiceAPI_GetServiceByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListServicesByField provides a mock function with given fields: ctx, namespace, fieldSelector
func (_m *MockServiceAPI) ListServicesByField(ctx context.Context, namespace string, fieldSelector string) ([]v1.Service, error) {
	ret := _m.Called(ctx, namespace, fieldSelector)

	if len(ret) == 0 {
		panic("no return value specified for ListServicesByField")
	}

	var r0 []v1.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]v1.Service, error)); ok {
		return rf(ctx, namespace, fieldSelector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []v1.Service); ok {
		r0 = rf(ctx, namespace, fieldSelector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, fieldSelector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceAPI_ListServicesByField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServicesByField'
type MockServiceAPI_ListServicesByField_Call struct {
	*mock.Call
}

// ListServicesByField is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - fieldSelector string
func (_e *MockServiceAPI_Expecter) ListServicesByField(ctx interface{}, namespace interface{}, fieldSelector interface{}) *MockServiceAPI_ListServicesByField_Call {
	return &MockServiceAPI_ListServicesByField_Call{Call: _e.mock.On("ListServicesByField", ctx, namespace, fieldSelector)}
}

func (_c *MockServiceAPI_ListServicesByField_Call) Run(run func(ctx context.Context, namespace string, fieldSelector string)) *MockServiceAPI_ListServicesByField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServiceAPI_ListServicesByField_Call) Return(_a0 []v1.Service, _a1 error) *MockServiceAPI_ListServicesByField_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceAPI_ListServicesByField_Call) RunAndReturn(run func(context.Context, string, string) ([]v1.Service, error)) *MockServiceAPI_ListServicesByField_Call {
	_c.Call.Return(run)
	return _c
}

// ListServicesByLabel provides a mock function with given fields: ctx, namespace, labelSelector
func (_m *MockServiceAPI) ListServicesByLabel(ctx context.Context, namespace string, labelSelector string) ([]v1.Service, error) {
	ret := _m.Called(ctx, namespace, labelSelector)

	if len(ret) == 0 {
		panic("no return value specified for ListServicesByLabel")
	}

	var r0 []v1.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]v1.Service, error)); ok {
		return rf(ctx, namespace, labelSelector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []v1.Service); ok {
		r0 = rf(ctx, namespace, labelSelector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, labelSelector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceAPI_ListServicesByLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServicesByLabel'
type MockServiceAPI_ListServicesByLabel_Call struct {
	*mock.Call
}

// ListServicesByLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - labelSelector string
func (_e *MockServiceAPI_Expecter) ListServicesByLabel(ctx interface{}, namespace interface{}, labelSelector interface{}) *MockServiceAPI_ListServicesByLabel_Call {
	return &MockServiceAPI_ListServicesByLabel_Call{Call: _e.mock.On("ListServicesByLabel", ctx, namespace, labelSelector)}
}

func (_c *MockServiceAPI_ListServicesByLabel_Call) Run(run func(ctx context.Context, namespace string, labelSelector string)) *MockServiceAPI_ListServicesByLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServiceAPI_ListServicesByLabel_Call) Return(_a0 []v1.Service, _a1 error) *MockServiceAPI_ListServicesByLabel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceAPI_ListServicesByLabel_Call) RunAndReturn(run func(context.Context, string, string) ([]v1.Service, error)) *MockServiceAPI_ListServicesByLabel_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceAPI creates a new instance of MockServiceAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceAPI {
	mock := &MockServiceAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
